import json

NB = '/mnt/c/Users/sefak/OneDrive/Documents/sefakarabas/OneDrive/Desktop/Dataset-2/shrub_pipeline.ipynb'
with open(NB, encoding='utf-8') as f:
    nb = json.load(f)

# Cell 5 is the environment check code cell
target_idx = None
for i, cell in enumerate(nb['cells']):
    src = ''.join(cell.get('source', []))
    if 'Environment Check' in src and 'REQUIRED' in src and cell['cell_type'] == 'code':
        target_idx = i
        break
print(f'Env check cell at index: {target_idx}')

lines = []
lines.append('import importlib\n')
lines.append('import subprocess, sys\n')
lines.append('\n')
lines.append('# ------------------------------------------------------------------ options --\n')
lines.append('# Set True to trigger optional actions below\n')
lines.append('TRY_GEE_AUTH = False   # run ee.Authenticate() + ee.Initialize()\n')
lines.append('INSTALL_SAM  = False   # pip-install segment-anything if missing\n')
lines.append('# ----------------------------------------------------------------------------\n')
lines.append('\n')
lines.append('REQUIRED = {\n')
lines.append('    "numpy":              "numpy",\n')
lines.append('    "pandas":             "pandas",\n')
lines.append('    "scipy":              "scipy",\n')
lines.append('    "sklearn":            "scikit-learn",\n')
lines.append('    "xgboost":            "xgboost",\n')
lines.append('    "optuna":             "optuna",\n')
lines.append('    "joblib":             "joblib",\n')
lines.append('    "rasterio":           "rasterio",\n')
lines.append('    "geopandas":          "geopandas",\n')
lines.append('    "shapely":            "shapely",\n')
lines.append('    "cv2":                "opencv-python",\n')
lines.append('    "matplotlib":         "matplotlib",\n')
lines.append('    "torch":              "torch",\n')
lines.append('    "torchvision":        "torchvision",\n')
lines.append('    "PIL":                "Pillow",\n')
lines.append('    "planetary_computer": "planetary-computer",\n')
lines.append('    "pystac_client":      "pystac-client",\n')
lines.append('}\n')
lines.append('OPTIONAL = {\n')
lines.append('    "ee":               "earthengine-api",\n')
lines.append('    "segment_anything": "segment-anything",\n')
lines.append('}\n')
lines.append('\n')
lines.append('log_section("2. Environment Check")\n')
lines.append('\n')
lines.append('# -- Required packages -------------------------------------------------------\n')
lines.append('all_ok = True\n')
lines.append('for mod, pkg in REQUIRED.items():\n')
lines.append('    try:\n')
lines.append('        m   = importlib.import_module(mod)\n')
lines.append('        ver = getattr(m, "__version__", "?")\n')
lines.append('        log(f"  OK    {pkg:<25} {ver}")\n')
lines.append('    except ImportError:\n')
lines.append('        log(f"  MISS  {pkg:<25} MISSING - pip install {pkg}", level="warning")\n')
lines.append('        all_ok = False\n')
lines.append('\n')
lines.append('# -- Optional packages -------------------------------------------------------\n')
lines.append('log("")\n')
lines.append('sam_installed = False\n')
lines.append('for mod, pkg in OPTIONAL.items():\n')
lines.append('    try:\n')
lines.append('        m   = importlib.import_module(mod)\n')
lines.append('        ver = getattr(m, "__version__", "?")\n')
lines.append('        log(f"  OK    {pkg:<25} {ver}  [optional]")\n')
lines.append('        if mod == "segment_anything":\n')
lines.append('            sam_installed = True\n')
lines.append('    except ImportError:\n')
lines.append('        log(f"  -     {pkg:<25} not installed [optional]")\n')
lines.append('\n')
lines.append('# -- Install segment-anything (optional) ------------------------------------\n')
lines.append('if INSTALL_SAM and not sam_installed:\n')
lines.append('    log("")\n')
lines.append('    log("  Installing segment-anything from Meta GitHub...")\n')
lines.append('    _res = subprocess.run(\n')
lines.append('        [sys.executable, "-m", "pip", "install", "-q",\n')
lines.append('         "git+https://github.com/facebookresearch/segment-anything.git"],\n')
lines.append('        capture_output=True, text=True\n')
lines.append('    )\n')
lines.append('    if _res.returncode == 0:\n')
lines.append('        log("  segment-anything installed successfully.")\n')
lines.append('        log("  NOTE: download checkpoint manually:")\n')
lines.append('        log("    wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth")\n')
lines.append('    else:\n')
lines.append('        log(f"  Install failed:\\n{_res.stderr[:400]}", level="error")\n')
lines.append('elif INSTALL_SAM and sam_installed:\n')
lines.append('    log("  segment-anything already installed -- skipping.")\n')
lines.append('\n')
lines.append('# -- GPU / CUDA --------------------------------------------------------------\n')
lines.append('import torch\n')
lines.append('cuda_info = (\n')
lines.append('    f"CUDA {torch.version.cuda} - {torch.cuda.get_device_name(0)}"\n')
lines.append('    if torch.cuda.is_available() else "CPU only"\n')
lines.append(')\n')
lines.append('log(f"\\n  GPU  : {cuda_info}")\n')
lines.append('status = "OK - all required packages present" if all_ok else "ERROR - missing packages"\n')
lines.append('log(f"  ENV  : {status}")\n')
lines.append('\n')
lines.append('# -- Google Earth Engine authentication (optional) --------------------------\n')
lines.append('log("")\n')
lines.append('if TRY_GEE_AUTH:\n')
lines.append('    try:\n')
lines.append('        import ee\n')
lines.append('        log("  GEE  : Authenticating... (browser window may open)")\n')
lines.append('        ee.Authenticate()\n')
lines.append('        ee.Initialize(project="ee-sefakarabas")\n')
lines.append('        log("  GEE  : Authenticated and initialised OK (project=ee-sefakarabas)")\n')
lines.append('    except Exception as _e:\n')
lines.append('        log(f"  GEE  : Authentication failed -- {_e}", level="warning")\n')
lines.append('        log("         Run: earthengine authenticate  (in terminal)", level="warning")\n')
lines.append('else:\n')
lines.append('    try:\n')
lines.append('        import ee\n')
lines.append('        ee.Initialize(project="ee-sefakarabas")\n')
lines.append('        log("  GEE  : Already authenticated (initialised OK)")\n')
lines.append('    except Exception:\n')
lines.append('        log("  GEE  : Not authenticated (set TRY_GEE_AUTH=True to authenticate)")\n')

nb['cells'][target_idx]['source'] = lines

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=True)

print(f'Cell {target_idx} updated')
src = ''.join(lines)
try:
    compile(src, '<cell>', 'exec')
    print('Syntax check: OK')
except SyntaxError as e:
    print(f'Syntax check FAILED: {e}')
