import json

NB = '/mnt/c/Users/sefak/OneDrive/Documents/sefakarabas/OneDrive/Desktop/Dataset-2/shrub_pipeline.ipynb'
with open(NB, encoding='utf-8') as f:
    nb = json.load(f)

target_idx = None
for i, cell in enumerate(nb['cells']):
    src = ''.join(cell.get('source', []))
    if 'all_sites_overview' in src and cell['cell_type'] == 'code':
        target_idx = i
        break

print(f'Found viz cell at index: {target_idx}')

lines = []
lines.append('import matplotlib.pyplot as plt\n')
lines.append('import matplotlib.patches as mpatches\n')
lines.append('from matplotlib.colors import ListedColormap\n')
lines.append('\n')
lines.append('log_section("7. Visualisation -- Site by Site")\n')
lines.append('\n')
lines.append('SHRUB_COLOR  = "#1db954"   # vivid green = shrub\n')
lines.append('NOSHRUB_COLOR = "#d0d0d0"  # light grey  = non-shrub\n')
lines.append('CMAP_BIN = ListedColormap([NOSHRUB_COLOR, SHRUB_COLOR])\n')
lines.append('\n')
lines.append('def read_rgb(naip_path):\n')
lines.append('    with rasterio.open(naip_path) as src:\n')
lines.append('        r = src.read(1).astype(np.float32)\n')
lines.append('        g = src.read(2).astype(np.float32)\n')
lines.append('        b = src.read(3).astype(np.float32)\n')
lines.append('    rgb = np.stack([r, g, b], axis=-1)\n')
lines.append('    for c in range(3):\n')
lines.append('        lo, hi = np.percentile(rgb[..., c], [2, 98])\n')
lines.append('        rgb[..., c] = np.clip((rgb[..., c] - lo) / (hi - lo), 0, 1) if hi > lo else 0\n')
lines.append('    return rgb\n')
lines.append('\n')
lines.append('def draw_mask_panel(ax, mask, r_info, meta, fontsize=10):\n')
lines.append('    """Show binary mask as 2-colour image with legend and stats."""\n')
lines.append('    n_shrub = int(mask.sum())\n')
lines.append('    pct     = 100.0 * n_shrub / mask.size\n')
lines.append('    ax.imshow(mask, cmap=CMAP_BIN, vmin=0, vmax=1, aspect="auto", interpolation="nearest")\n')
lines.append('    legend_elems = [\n')
lines.append('        mpatches.Patch(facecolor=SHRUB_COLOR,  edgecolor="none",\n')
lines.append('                       label=f"Shrub  {r_info[\'shrub_ha\']} ha  ({pct:.1f}%)"),\n')
lines.append('        mpatches.Patch(facecolor=NOSHRUB_COLOR, edgecolor="#888",\n')
lines.append('                       label="Non-shrub"),\n')
lines.append('    ]\n')
lines.append('    ax.legend(handles=legend_elems, loc="lower left",\n')
lines.append('              fontsize=max(fontsize - 2, 6), framealpha=0.85,\n')
lines.append('              edgecolor="#aaa")\n')
lines.append('    ax.set_title(\n')
lines.append('        f"Binary Shrub Mask  (thr = {meta[\'cls_threshold\']})\\n"\n')
lines.append('        f"{r_info[\'shrub_ha\']} ha shrub  |  {pct:.1f}% of raster",\n')
lines.append('        fontsize=fontsize\n')
lines.append('    )\n')
lines.append('    ax.axis("off")\n')
lines.append('\n')
lines.append('ok_results = [r for r in results if r["status"] == "OK"]\n')
lines.append('\n')
lines.append('# -- One figure per site --------------------------------------------------\n')
lines.append('site_paths = []\n')
lines.append('for r in ok_results:\n')
lines.append('    site   = r["site"]\n')
lines.append('    naip_p = BASE / site / "NAIP_3DEP_product" / SITES[site]["naip"]\n')
lines.append('    rgb    = read_rgb(naip_p)\n')
lines.append('    prob   = r["prob_map"]\n')
lines.append('    mask   = r["mask"]\n')
lines.append('    H, W   = mask.shape\n')
lines.append('\n')
lines.append('    aspect  = H / W\n')
lines.append('    fig_w   = 15\n')
lines.append('    img_h   = fig_w / 3 * aspect\n')
lines.append('    fig_h   = max(img_h + 1.2, 3.5)\n')
lines.append('\n')
lines.append('    fig, axes = plt.subplots(1, 3, figsize=(fig_w, fig_h))\n')
lines.append('\n')
lines.append('    # Panel 1: NAIP RGB\n')
lines.append('    axes[0].imshow(rgb, aspect="auto")\n')
lines.append('    axes[0].set_title(f"{site}\\nNAIP RGB", fontsize=10, fontweight="bold")\n')
lines.append('    axes[0].axis("off")\n')
lines.append('\n')
lines.append('    # Panel 2: Probability map\n')
lines.append('    im = axes[1].imshow(prob, cmap="RdYlGn", vmin=0, vmax=1, aspect="auto")\n')
lines.append('    cbar = plt.colorbar(im, ax=axes[1], fraction=0.046, pad=0.04)\n')
lines.append('    cbar.set_label("Shrub probability", fontsize=8)\n')
lines.append('    cbar.ax.tick_params(labelsize=7)\n')
lines.append('    axes[1].set_title(f"V12 Probability\\np50={r[\'p50\']}  p95={r[\'p95\']}", fontsize=10)\n')
lines.append('    axes[1].axis("off")\n')
lines.append('\n')
lines.append('    # Panel 3: Binary mask (2-colour map + legend)\n')
lines.append('    draw_mask_panel(axes[2], mask, r, meta, fontsize=10)\n')
lines.append('\n')
lines.append('    fig.suptitle(f"V12 XGBoost Shrub Detection -- {site}  ({H}x{W} px)",\n')
lines.append('                 fontsize=12, fontweight="bold", y=1.01)\n')
lines.append('    plt.tight_layout()\n')
lines.append('\n')
lines.append('    site_png = OUT_ROOT / site / f"{site.lower()}_v12_overview.png"\n')
lines.append('    plt.savefig(site_png, dpi=150, bbox_inches="tight", facecolor="white")\n')
lines.append('    site_paths.append(site_png)\n')
lines.append('    plt.show()\n')
lines.append('    log(f"  [{site}] saved overview: {site_png.name}")\n')
lines.append('\n')
lines.append('# -- Combined overview -----------------------------------------------------\n')
lines.append('n = len(ok_results)\n')
lines.append('fig2, axes2 = plt.subplots(n, 3, figsize=(15, 4 * n))\n')
lines.append('if n == 1:\n')
lines.append('    axes2 = [axes2]\n')
lines.append('for row, r in enumerate(ok_results):\n')
lines.append('    site   = r["site"]\n')
lines.append('    naip_p = BASE / site / "NAIP_3DEP_product" / SITES[site]["naip"]\n')
lines.append('    rgb    = read_rgb(naip_p)\n')
lines.append('    prob   = r["prob_map"]\n')
lines.append('    mask   = r["mask"]\n')
lines.append('    axes2[row][0].imshow(rgb)\n')
lines.append('    axes2[row][0].set_title(f"{site}\\nNAIP RGB", fontsize=8)\n')
lines.append('    axes2[row][0].axis("off")\n')
lines.append('    im = axes2[row][1].imshow(prob, cmap="RdYlGn", vmin=0, vmax=1)\n')
lines.append('    cbar2 = plt.colorbar(im, ax=axes2[row][1], fraction=0.046, pad=0.04)\n')
lines.append('    cbar2.ax.tick_params(labelsize=6)\n')
lines.append('    axes2[row][1].set_title(f"V12 Probability\\np50={r[\'p50\']}  p95={r[\'p95\']}", fontsize=8)\n')
lines.append('    axes2[row][1].axis("off")\n')
lines.append('    draw_mask_panel(axes2[row][2], mask, r, meta, fontsize=8)\n')
lines.append('fig2.suptitle("V12 XGBoost Shrub Detection -- All Sites", fontsize=12, y=1.01)\n')
lines.append('fig2.tight_layout()\n')
lines.append('overview_path = OUT_ROOT / "all_sites_overview.png"\n')
lines.append('fig2.savefig(overview_path, dpi=150, bbox_inches="tight")\n')
lines.append('plt.show()\n')
lines.append('log(f"  Saved combined overview : {overview_path}")\n')
lines.append('\n')
lines.append('# -- Probability histograms ------------------------------------------------\n')
lines.append('fig3, axes3 = plt.subplots(2, 3, figsize=(14, 7))\n')
lines.append('axes3 = axes3.flatten()\n')
lines.append('for i, r in enumerate(ok_results):\n')
lines.append('    ax = axes3[i]\n')
lines.append('    ax.hist(r["prob_map"].flatten(), bins=50, color="steelblue", edgecolor="none", alpha=0.8)\n')
lines.append('    ax.axvline(meta["cls_threshold"], color="red", linestyle="--",\n')
lines.append('               label=f"thr={meta[\'cls_threshold\']}")\n')
lines.append('    ax.set_title(r["site"], fontsize=9)\n')
lines.append('    ax.set_xlabel("Shrub probability")\n')
lines.append('    ax.set_ylabel("Pixel count")\n')
lines.append('    ax.legend(fontsize=8)\n')
lines.append('for j in range(len(ok_results), 6):\n')
lines.append('    axes3[j].set_visible(False)\n')
lines.append('fig3.suptitle("V12 Probability Distributions -- All Sites", fontsize=11)\n')
lines.append('fig3.tight_layout()\n')
lines.append('hist_path = OUT_ROOT / "probability_histograms.png"\n')
lines.append('fig3.savefig(hist_path, dpi=150, bbox_inches="tight")\n')
lines.append('plt.show()\n')
lines.append('log(f"  Saved histograms: {hist_path}")\n')

nb['cells'][target_idx]['source'] = lines

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=True)

print(f'Cell {target_idx} updated')
src = ''.join(lines)
try:
    compile(src, '<cell>', 'exec')
    print('Syntax check: OK')
except SyntaxError as e:
    print(f'Syntax check FAILED: {e}')
