import json

NB = '/mnt/c/Users/sefak/OneDrive/Documents/sefakarabas/OneDrive/Desktop/Dataset-2/shrub_pipeline.ipynb'
with open(NB, encoding='utf-8') as f:
    nb = json.load(f)

target_idx = None
for i, cell in enumerate(nb['cells']):
    src = ''.join(cell.get('source', []))
    if 'all_sites_overview' in src and cell['cell_type'] == 'code':
        target_idx = i
        break

print(f'Found viz cell at index: {target_idx}')

# Write correct source — \n inside string literals must be the 2-char escape
# We use raw strings for lines containing \n inside f-strings
lines = []
lines.append('import matplotlib.pyplot as plt\n')
lines.append('import matplotlib.gridspec as gridspec\n')
lines.append('\n')
lines.append('log_section("7. Visualisation -- Site by Site")\n')
lines.append('\n')
lines.append('def read_rgb(naip_path):\n')
lines.append('    with rasterio.open(naip_path) as src:\n')
lines.append('        r = src.read(1).astype(np.float32)\n')
lines.append('        g = src.read(2).astype(np.float32)\n')
lines.append('        b = src.read(3).astype(np.float32)\n')
lines.append('    rgb = np.stack([r, g, b], axis=-1)\n')
lines.append('    for c in range(3):\n')
lines.append('        lo, hi = np.percentile(rgb[..., c], [2, 98])\n')
lines.append('        rgb[..., c] = np.clip((rgb[..., c] - lo) / (hi - lo), 0, 1) if hi > lo else 0\n')
lines.append('    return rgb\n')
lines.append('\n')
lines.append('ok_results = [r for r in results if r["status"] == "OK"]\n')
lines.append('\n')
lines.append('# -- One figure per site --------------------------------------------------\n')
lines.append('site_paths = []\n')
lines.append('for r in ok_results:\n')
lines.append('    site   = r["site"]\n')
lines.append('    naip_p = BASE / site / "NAIP_3DEP_product" / SITES[site]["naip"]\n')
lines.append('    rgb    = read_rgb(naip_p)\n')
lines.append('    prob   = r["prob_map"]\n')
lines.append('    mask   = r["mask"]\n')
lines.append('    H, W   = mask.shape\n')
lines.append('\n')
lines.append('    aspect  = H / W\n')
lines.append('    fig_w   = 15\n')
lines.append('    img_h   = fig_w / 3 * aspect\n')
lines.append('    fig_h   = max(img_h + 1.0, 3.5)\n')
lines.append('\n')
lines.append('    fig, axes = plt.subplots(1, 3, figsize=(fig_w, fig_h))\n')
lines.append('\n')
lines.append('    axes[0].imshow(rgb, aspect="auto")\n')
# \n inside f-string — must be \\n in this Python source so it becomes \n in the notebook cell
lines.append('    axes[0].set_title(f"{site}\\nNAIP RGB", fontsize=10, fontweight="bold")\n')
lines.append('    axes[0].axis("off")\n')
lines.append('\n')
lines.append('    im = axes[1].imshow(prob, cmap="RdYlGn", vmin=0, vmax=1, aspect="auto")\n')
lines.append('    plt.colorbar(im, ax=axes[1], fraction=0.046, pad=0.04)\n')
lines.append('    axes[1].set_title(f"V12 Probability\\np50={r[\'p50\']}  p95={r[\'p95\']}", fontsize=10)\n')
lines.append('    axes[1].axis("off")\n')
lines.append('\n')
lines.append('    overlay = np.zeros((H, W, 4), dtype=np.float32)\n')
lines.append('    overlay[mask == 1] = [0.0, 1.0, 0.3, 0.45]\n')
lines.append('    axes[2].imshow(rgb, aspect="auto")\n')
lines.append('    axes[2].imshow(overlay, aspect="auto")\n')
lines.append('    axes[2].set_title(\n')
lines.append('        f"Binary Mask (thr={meta[\'cls_threshold\']})\\n{r[\'shrub_ha\']} ha shrub",\n')
lines.append('        fontsize=10\n')
lines.append('    )\n')
lines.append('    axes[2].axis("off")\n')
lines.append('\n')
lines.append('    fig.suptitle(f"V12 XGBoost Shrub Detection -- {site}  ({H}x{W} px)",\n')
lines.append('                 fontsize=12, fontweight="bold", y=1.01)\n')
lines.append('    plt.tight_layout()\n')
lines.append('\n')
lines.append('    site_png = OUT_ROOT / site / f"{site.lower()}_v12_overview.png"\n')
lines.append('    plt.savefig(site_png, dpi=150, bbox_inches="tight", facecolor="white")\n')
lines.append('    site_paths.append(site_png)\n')
lines.append('    plt.show()\n')
lines.append('    log(f"  [{site}] saved overview: {site_png.name}")\n')
lines.append('\n')
lines.append('# -- Combined overview -----------------------------------------------------\n')
lines.append('n = len(ok_results)\n')
lines.append('fig2, axes2 = plt.subplots(n, 3, figsize=(15, 4 * n))\n')
lines.append('if n == 1:\n')
lines.append('    axes2 = [axes2]\n')
lines.append('for row, r in enumerate(ok_results):\n')
lines.append('    site   = r["site"]\n')
lines.append('    naip_p = BASE / site / "NAIP_3DEP_product" / SITES[site]["naip"]\n')
lines.append('    rgb    = read_rgb(naip_p)\n')
lines.append('    prob   = r["prob_map"]\n')
lines.append('    mask   = r["mask"]\n')
lines.append('    axes2[row][0].imshow(rgb)\n')
lines.append('    axes2[row][0].set_title(f"{site}\\nNAIP RGB", fontsize=8)\n')
lines.append('    axes2[row][0].axis("off")\n')
lines.append('    im = axes2[row][1].imshow(prob, cmap="RdYlGn", vmin=0, vmax=1)\n')
lines.append('    plt.colorbar(im, ax=axes2[row][1], fraction=0.046, pad=0.04)\n')
lines.append('    axes2[row][1].set_title(f"V12 Probability\\np50={r[\'p50\']}  p95={r[\'p95\']}", fontsize=8)\n')
lines.append('    axes2[row][1].axis("off")\n')
lines.append('    overlay = np.zeros((*mask.shape, 4), dtype=np.float32)\n')
lines.append('    overlay[mask == 1] = [0.0, 1.0, 0.3, 0.45]\n')
lines.append('    axes2[row][2].imshow(rgb)\n')
lines.append('    axes2[row][2].imshow(overlay)\n')
lines.append('    axes2[row][2].set_title(\n')
lines.append('        f"Binary Mask (thr={meta[\'cls_threshold\']})\\n{r[\'shrub_ha\']} ha shrub",\n')
lines.append('        fontsize=8\n')
lines.append('    )\n')
lines.append('    axes2[row][2].axis("off")\n')
lines.append('fig2.suptitle("V12 XGBoost Shrub Detection -- All Sites", fontsize=12, y=1.01)\n')
lines.append('fig2.tight_layout()\n')
lines.append('overview_path = OUT_ROOT / "all_sites_overview.png"\n')
lines.append('fig2.savefig(overview_path, dpi=150, bbox_inches="tight")\n')
lines.append('plt.show()\n')
lines.append('log(f"  Saved combined overview : {overview_path}")\n')
lines.append('\n')
lines.append('# -- Probability histograms ------------------------------------------------\n')
lines.append('fig3, axes3 = plt.subplots(2, 3, figsize=(14, 7))\n')
lines.append('axes3 = axes3.flatten()\n')
lines.append('for i, r in enumerate(ok_results):\n')
lines.append('    ax = axes3[i]\n')
lines.append('    ax.hist(r["prob_map"].flatten(), bins=50, color="steelblue", edgecolor="none", alpha=0.8)\n')
lines.append('    ax.axvline(meta["cls_threshold"], color="red", linestyle="--",\n')
lines.append('               label=f"thr={meta[\'cls_threshold\']}")\n')
lines.append('    ax.set_title(r["site"], fontsize=9)\n')
lines.append('    ax.set_xlabel("Shrub probability")\n')
lines.append('    ax.set_ylabel("Pixel count")\n')
lines.append('    ax.legend(fontsize=8)\n')
lines.append('for j in range(len(ok_results), 6):\n')
lines.append('    axes3[j].set_visible(False)\n')
lines.append('fig3.suptitle("V12 Probability Distributions -- All Sites", fontsize=11)\n')
lines.append('fig3.tight_layout()\n')
lines.append('hist_path = OUT_ROOT / "probability_histograms.png"\n')
lines.append('fig3.savefig(hist_path, dpi=150, bbox_inches="tight")\n')
lines.append('plt.show()\n')
lines.append('log(f"  Saved histograms: {hist_path}")\n')

nb['cells'][target_idx]['source'] = lines

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=True)

print(f'Cell {target_idx} fixed successfully')

src = ''.join(lines)
try:
    compile(src, '<cell>', 'exec')
    print('Syntax check: OK')
except SyntaxError as e:
    print(f'Syntax check FAILED: {e}')
